version: '3.6'

services:

  db:
    image: mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_DATABASE: reseller-db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080