version: '3.6'

services:

  app:
    build: .
    command: [ "./wait-for-it.sh", "db:3306", "--", "bash", "app.sh" ]
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - db
      - adminer
    networks:
      - backend

  db:
    image: mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_DATABASE: reseller-db
    networks:
      - backend
    security_opt:
      - seccomp:unconfined

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
